In [1]:
import pandas as pd

In [2]:
df_exams = pd.read_csv('StudentsPerformance.csv')
df_exams.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

In [3]:
df_exams['language score'] = 70
df_exams

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,language score
0,female,group B,bachelor's degree,standard,none,72,72,74,70
1,female,group C,some college,standard,completed,69,90,88,70
2,female,group B,master's degree,standard,none,90,95,93,70
3,male,group A,associate's degree,free/reduced,none,47,57,44,70
4,male,group C,some college,standard,none,76,78,75,70
...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95,70
996,male,group C,high school,free/reduced,none,62,55,55,70
997,female,group C,high school,free/reduced,completed,59,71,65,70
998,female,group D,some college,standard,completed,68,78,77,70
999,female,group D,some college,free/reduced,none,77,86,86,70

# Adding a new column with an array

In [4]:
import numpy as np

In [6]:
language_score = np.arange(0, 1000)

In [7]:
len(language_score)

1000

In [9]:
df_exams['language score'] = language_score
df_exams

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,language score
0,female,group B,bachelor's degree,standard,none,72,72,74,0
1,female,group C,some college,standard,completed,69,90,88,1
2,female,group B,master's degree,standard,none,90,95,93,2
3,male,group A,associate's degree,free/reduced,none,47,57,44,3
4,male,group C,some college,standard,none,76,78,75,4
...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95,995
996,male,group C,high school,free/reduced,none,62,55,55,996
997,female,group C,high school,free/reduced,completed,59,71,65,997
998,female,group D,some college,standard,completed,68,78,77,998
999,female,group D,some college,free/reduced,none,77,86,86,999

In [11]:
int_language_score = np.random.randint(1, 100, size=1000)

In [12]:
print(min(int_language_score))
print(max(int_language_score))

1
99

In [13]:
df_exams['language score'] = int_language_score
df_exams

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,language score
0,female,group B,bachelor's degree,standard,none,72,72,74,25
1,female,group C,some college,standard,completed,69,90,88,91
2,female,group B,master's degree,standard,none,90,95,93,84
3,male,group A,associate's degree,free/reduced,none,47,57,44,72
4,male,group C,some college,standard,none,76,78,75,48
...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95,51
996,male,group C,high school,free/reduced,none,62,55,55,64
997,female,group C,high school,free/reduced,completed,59,71,65,44
998,female,group D,some college,standard,completed,68,78,77,53
999,female,group D,some college,free/reduced,none,77,86,86,79

In [14]:
np.random.uniform(1, 100, size=1000)

array([79.9762967 , 55.68953536, 52.48703968, 27.76871364, 17.22599746,
       60.95280213, 43.81048067, 68.73808907, 25.32758963, 98.2215222 ,
       63.11505267, 25.82437865,  3.30416837, 64.59407184, 14.93462631,
       47.44009681, 40.55646705, 61.47461227, 54.91945161, 94.93585745,
       21.01048487, 33.10894643, 38.20762291, 71.88940159, 12.10295779,
       99.75942386, 69.45910572, 11.51633923, 81.63882602, 37.8574655 ,
       96.19021727, 93.26509381, 65.41469978, 63.13713373, 66.71897667,
        9.423632  , 77.57915081, 85.624691  , 19.27205443, 22.63527902,
       83.78446024,  6.64098087, 87.76453456, 44.52102519, 46.74177883,
       87.56961452, 32.33213123, 78.09062047, 41.79560697, 62.11867905,
       96.39110246, 76.99996505, 65.10336259, 72.15575566, 45.51086905,
       19.22598026, 93.02717327, 10.59777597, 47.14430745, 84.18428937,
       47.23692441, 57.04738173, 88.57086794, 31.5732879 , 20.5077156 ,
       35.96075437, 15.287383  , 24.45760318, 29.46822723, 10.82974693,
       75.62072541, 46.03402888, 16.4197917 , 14.16666613, 43.17287266,
       54.5949424 , 36.16234517, 40.40232642, 42.10793709, 21.35574243,
       41.73857744, 27.27227654, 46.41287005, 13.21596532, 29.58560109,
       11.66230259, 87.68564923, 63.93688197, 36.00877398, 88.85052039,
       93.73117312, 69.23161924, 54.38167521, 82.99600627, 82.03255081,
       44.91053336, 51.22337036, 92.4066085 , 56.20866109, 37.30005753,
       17.35599798,  1.96823871, 71.04747942, 10.91583203, 86.71888793,
       36.03770804, 96.13765795, 79.95423972, 89.18552915, 57.67157248,
       41.81263847, 76.47723198, 49.57894485, 77.05019686, 75.36226757,
       70.60925905, 13.35463889, 58.04921116, 51.31407109, 77.36650611,
       79.18811389, 25.750743  , 95.50426577, 85.51261746, 21.81248293,
        9.23784873, 97.47396849, 95.21289686, 25.59253824, 43.1404927 ,
       61.45263691, 59.10286629, 91.925252  , 14.82373056, 36.76654612,
       15.5871176 , 96.31177882, 29.47032548, 76.6460414 , 37.24138139,
       28.86476295, 24.99055479, 53.75523764,  7.64030202, 50.98597217,
       76.35709527, 63.4655769 , 72.25106128, 19.73396449, 64.83272774,
       88.15042564, 29.46448607, 49.54991121, 54.74772314,  9.71220945,
       72.3194193 , 58.44393338, 40.03658636, 30.54897273, 21.76631491,
       19.09097316, 69.7502501 , 31.94651533, 83.92199569,  7.5854634 ,
       44.43254391, 60.81247417, 61.14094437, 29.15951128,  8.57056958,
       60.86797527, 48.85343585, 29.55588822, 22.63909997, 52.07635887,
       26.00194575, 42.80596891, 19.09834778, 87.32828828,  5.66568875,
       93.24301221,  5.67840877, 24.97406588,  2.00773173, 51.09369682,
       44.35034112, 45.52342355, 65.73621985, 97.75389212,  2.59952926,
       57.96828043, 11.90656305,  3.93952608, 57.04220066, 93.89830942,
       72.45629202, 34.0109051 , 33.093405  , 45.00670326, 68.01883978,
       80.36802891, 24.55896852,  1.52072572, 42.05656844, 43.94840726,
       13.2374871 , 54.93190527, 50.62681987, 36.07495541, 95.32991505,
       36.9073953 ,  5.63852711, 48.78878576, 96.24919551, 95.27467783,
       18.35069717, 53.36790054, 36.98627464, 66.94263193,  8.87495934,
       55.77624094, 93.27712403, 81.94150855, 86.25369311, 32.43317098,
        2.59964372, 75.91259684, 45.69304329, 82.00995958, 35.13778056,
       48.29728504, 73.87812133, 32.50805327, 80.39815293, 52.02723992,
        2.05793403, 55.18715423, 57.92988075, 46.71832543, 38.14730942,
       15.25877583, 14.75018996, 10.62646748, 94.94205049, 19.46124362,
       59.98146171, 28.18782727, 17.6721825 , 55.62618342, 25.27995717,
        5.55306072, 22.20676525, 57.41564242, 97.17442095, 46.58530075,
       96.2983662 , 59.89981107, 91.09383781, 11.02404703, 43.27452593,
        7.37780403, 13.80139195, 11.42382495,  9.99072298, 37.61801618,
       33.53129174,  9.11389377, 15.07337846, 39.48383345, 37.17826152,
       54.88117325,  2.76620071, 65.3649211 , 12.52340909, 19.16562173,
       57.83795992, 59.43099005, 29.35195622, 43.8505657 , 49.09564547,
       89.07595327, 10.39232544, 14.57919266, 10.34180121, 85.36726087,
       82.7134305 , 31.44734204, 51.18641855, 44.3247444 , 98.84169268,
       16.20742517, 20.54124215,  6.08637435, 65.38329709, 77.27462758,
       84.72646694, 28.6738775 ,  2.26696389, 29.75637882, 69.30179512,
       58.52204673, 39.005469  ,  6.94402493, 48.74480188, 51.43647787,
       73.48013368, 19.65013048, 93.11018498, 76.88722422, 17.24111397,
       58.99137832,  1.93175987, 83.99427842, 64.81450246, 88.98377551,
       33.09338225, 21.58482179, 37.61763534, 33.94488037,  2.07774888,
       45.99601849,  1.02960736, 16.50867463, 78.70077762, 92.00973794,
       65.73369769, 62.86293279, 73.08016129, 59.30613219, 99.81076658,
        6.83608344, 81.42539383, 76.94766626, 81.11470511, 53.38875248,
       62.80110428, 36.4380668 , 91.28876993, 79.90306067, 28.56282319,
       39.14667224, 62.43623592, 58.5725852 , 11.80077379, 88.96748562,
        6.17519075, 71.59139236, 31.60680552, 52.7119251 , 65.61363954,
       44.6858689 , 61.17474667, 83.30468528, 86.36636241, 40.17720591,
       77.78989397, 65.99684718, 65.56429484, 44.88502754, 42.77692922,
       49.05469068, 86.90438615, 17.26305181, 84.96349696, 75.45323558,
       62.88587758, 44.49180647, 90.69545868, 96.04095011, 21.18945565,
       95.13170796, 70.20714815, 12.75405231, 43.88659311, 55.18457892,
       86.83575601, 61.18102031, 65.72387044, 95.78735496, 95.06524176,
       50.97592109, 72.84332247, 86.19870458, 75.01441468, 48.6510313 ,
       23.28002316, 21.68563855, 49.20892104, 71.47121848, 81.54980837,
       39.21510278, 28.72100331, 63.38694296, 85.63688572, 43.80088327,
       84.79973912, 59.63906846, 52.07909725, 67.35852494, 39.58152495,
       86.93888865, 13.16901881, 49.43106101, 19.06426544, 10.44812992,
       15.38761166,  6.80275956, 53.46180795,  9.72440134, 59.33594993,
       28.29398719, 43.80340087, 16.82947641, 63.16566524, 43.34279526,
       77.92729926, 42.69731057, 55.54876326, 56.74393516, 80.54318536,
       22.09157558, 16.94712571,  7.18572318, 11.86824486, 35.54459563,
       25.69635402,  3.10721443, 48.22261472, 80.34723609, 89.08192527,
       63.0992397 , 62.58263767, 74.18713604, 27.10847389, 46.85106584,
       92.93344874, 14.37163913, 85.16343126, 84.50111572, 58.54118873,
       15.88133084, 78.94066813, 70.44105416,  6.8301881 , 91.69741332,
       30.81673498,  6.7981362 , 53.89536883,  3.83671768, 31.42233093,
        6.91908876, 23.57327596, 31.63999018, 54.26091134, 50.90978949,
       62.27354395, 13.17213978, 57.7503315 , 87.65706813, 80.5773851 ,
       17.90291055, 20.91100934,  6.8163331 , 93.77182134, 30.22805744,
       11.54807881, 43.76353371, 20.11032686, 79.3043621 , 42.27250196,
       48.81718651, 77.56976452,  7.50950175, 69.7111009 , 31.83237648,
       15.26489068, 37.22362373, 84.58277792, 49.24953617, 46.59236182,
       29.75978343, 89.82027911, 25.2518161 ,  6.1556547 , 14.38095664,
       34.24118159, 26.59313555, 88.3073679 , 97.68048313, 73.68429009,
       73.56686166, 11.67965801, 15.47878638, 22.8522674 , 62.92454514,
       67.54643682, 91.06473483,  4.77596226, 64.88758693, 21.72531748,
       26.3427617 , 98.153387  , 14.26780327, 71.4638787 , 45.41928646,
       81.10063174, 46.7952366 , 68.53004997, 22.25740901,  6.29860372,
        9.71170797,  9.28381353, 43.2472858 , 24.50733405, 17.37145336,
       91.37642067,  8.40313909, 43.5174074 , 34.4875052 , 89.13276078,
        3.69933998, 88.99925244, 35.81109448, 14.58979661, 97.90582661,
       58.92978737,  1.00560703, 74.94458195, 36.83822048,  5.02742977,
       50.24583688, 69.22278682, 96.15852644,  5.02306935, 48.13563488,
       54.29132754, 64.66029331, 29.24219876,  9.05116391, 38.958076  ,
       68.97987088, 86.84665041, 31.55023694, 51.77875552, 54.93865594,
       66.8237257 , 34.56185332, 64.06738577, 48.27001425, 24.5821082 ,
       87.52505764, 21.33359016, 18.79696645, 41.84270185, 79.74019538,
       91.09671486, 39.7600695 , 16.11631441, 73.26820051, 42.50505586,
       99.29027818,  9.76290108, 72.61594022, 10.07483797,  8.70324019,
       15.94185485, 49.78552215, 53.68001969, 92.24007021, 12.10549743,
       79.81126155, 96.13983903, 12.05983234, 59.42616841, 40.04859909,
       96.7375655 , 85.8920414 , 57.84108251, 87.17802661, 12.11899103,
        6.85681508, 57.04341501, 54.19459599, 80.19760823, 73.98991054,
       75.57962057, 20.86012501, 22.82948627, 51.68540123,  4.43151867,
       91.99721478, 92.92349583, 33.43795691, 87.42445678,  4.2439643 ,
       27.62363136,  6.93698448, 90.40284691, 88.443497  , 23.93382902,
       56.7378195 , 62.27051334, 57.18165635, 99.12142311, 96.13528599,
       55.40864108, 47.77676476, 59.99323468, 45.95531864, 29.45614599,
       41.39507752, 36.7449805 , 74.53495568, 93.97649273, 40.4844868 ,
       28.92811795, 40.29872021, 98.3829364 , 45.15165509, 78.13556936,
       79.97321174, 18.61085629, 82.39304972, 31.73270044, 73.23676488,
       83.47005079, 82.79933209, 94.2759053 , 54.87914598, 12.42645838,
       18.32593547, 88.74895939, 76.915869  , 58.14574996, 28.70684173,
       14.78316927, 34.90951123, 59.41626815, 44.86828746, 77.47449697,
       51.33210614, 25.26538126, 76.77788153, 76.78895128, 39.95676365,
       73.90696396, 57.22634013, 30.52545816, 45.61706898, 21.56931766,
       34.55610668, 52.97510263, 17.81175545, 49.95114431, 54.13666314,
       88.50650868, 77.89710437, 57.60677651, 96.67398458,  1.9180718 ,
       96.04265717, 39.01178275, 85.28020662, 99.34682465, 64.73749175,
       37.5648983 , 64.2115537 , 45.05414541, 52.56565669, 17.73715147,
       60.96753018, 44.4197653 ,  3.22407658, 30.73438745,  4.77128671,
       52.30891973, 93.9212306 , 26.44879973, 14.5190177 ,  5.22824246,
       80.27482691, 81.31616027,  9.71503615, 71.86012418, 93.72645348,
       68.9513561 , 53.90606802, 40.48237622, 13.34096753, 59.30091846,
       63.95743007, 58.44188577,  8.82781639, 39.2562267 , 51.70312551,
       65.07991267, 39.86197868, 43.05361208, 12.76794172, 80.13443899,
       74.48028912, 39.61195864, 10.44644645, 29.70218414, 47.84550486,
       20.98054209, 99.70979501, 32.57706952, 94.20026258, 41.16132516,
       67.66536966, 21.39438173, 67.49565762, 27.57292521, 71.08420903,
       46.51887704, 12.78222417,  1.22737244, 96.07262184, 13.79811676,
       78.31002031,  9.37811902, 36.65326933, 66.05653017, 73.51694879,
       24.91636125, 56.54564206, 66.09080712, 48.12821218, 91.26843376,
       72.21814813, 73.73273948,  6.62007661, 60.0941946 , 97.22845881,
       69.83677363, 42.66666941, 41.98411753, 38.26371978, 54.20405304,
       45.65307556, 54.74941233, 11.62033228, 75.94072172, 85.64048663,
       77.13794434, 70.32084527, 55.94443515, 73.43837033, 58.59386258,
       57.59767495, 99.37740491, 97.34517058,  9.12255969, 68.62699058,
        3.57152011, 89.38702033, 84.50238413, 30.51063456, 19.73116029,
       72.36758172, 87.67241477, 74.49482456, 80.86298069, 44.80770276,
       76.34360391, 64.54113013,  6.03119177, 68.04182783, 95.10276173,
       31.86132129, 87.76009849, 77.49931764, 79.5063122 , 96.16702257,
       19.03499282, 59.86807918, 89.86466033, 58.67487094, 69.49598903,
       99.66794934, 49.28687356, 58.84393763, 53.32631226, 61.17860572,
       73.76087402, 28.76206803, 65.24024868, 18.02019166, 21.95432598,
       64.34965431, 83.14540778,  6.30959648,  9.40258807, 17.82450398,
        1.67333605, 87.96091901, 51.00803113, 10.56712355,  6.17470097,
       34.08555293,  9.88901211, 90.01959395,  1.06482447, 82.50011583,
       53.95225798, 71.55748383,  2.08783158, 47.90505525, 40.70653152,
       55.4219054 , 76.63071676, 33.7649471 , 77.03831808, 82.03639952,
       72.41458198, 47.43835005, 63.66383196, 61.19527677, 28.52756896,
       89.51538456, 73.92991577, 33.1128085 ,  5.09263976, 32.9998018 ,
       62.73442562, 36.91009339, 65.31801332, 85.35971987,  5.87079425,
       39.92095426, 11.70876492, 65.43019699, 42.71227352,  3.34765697,
        8.26308673,  4.98532315, 28.30792321, 29.71248987, 21.86033686,
       44.29007425, 46.88258642, 53.62417131, 17.24864522, 53.29072024,
        8.49668406, 14.24032028, 59.68481144, 51.16026493,  1.74969117,
       14.38640443, 37.06273707, 83.57036418, 83.20782838,  9.37414649,
       10.3275621 , 33.03145556, 34.87489317, 46.31805413, 21.40810614,
       76.28456557, 70.1566539 , 27.27649792, 57.54637267, 92.46691117,
       46.93159261, 18.3593579 , 22.46066553, 30.52789513, 87.25305174,
       70.959801  ,  2.62058297, 59.55930153, 21.2662366 ,  6.03340363,
        8.13175141, 21.88522268, 80.24899365, 98.84488765, 25.54123387,
       22.53978378, 34.47608088, 42.68268022, 14.27210961, 57.69705057,
       79.30033625, 37.0320801 , 11.87183305, 82.85775647, 79.85211801,
       65.24983966, 62.38566666, 88.52772026, 38.31191885, 94.63578887,
       56.37583733, 35.09569979, 83.78398833, 75.18860872, 20.77102754,
       96.07613039, 49.62914048, 38.70172483, 71.56985142, 22.83964762,
       80.40368912, 65.96555623, 82.7443752 , 18.76411957, 75.30123816,
       48.72139865, 22.94239239, 79.17945709,  9.9959004 , 63.65825663,
       68.6901792 , 60.41803922, 46.58973314, 38.00483496, 61.83096733,
       55.46202922, 35.02757111, 59.12416222, 21.67592049, 11.65595962,
        6.66984032, 58.33431272,  4.59299982, 46.69748506, 68.28549171,
       89.25519155, 65.12974737, 78.34314923, 73.97563315, 39.82424185,
       68.96361617,  1.0156318 , 36.70282823,  5.56117727, 85.98247335,
       43.74330328, 12.40873718,  9.5867525 , 69.73539434, 48.10667276,
       26.30148423, 18.9931613 , 29.42565342, 30.59249215, 82.42470611,
       92.66094378, 17.55216892, 91.65637951, 27.34294803, 41.74005529,
       87.88055335, 46.48633288, 34.86357751,  5.34965978, 91.35106397,
       47.83721056, 19.8226341 , 66.34958562, 43.30072301, 35.22285683,
       54.51638789,  2.52006676, 58.43745751, 93.06587066, 43.89137394,
       56.34675213, 52.44909098, 44.62942912, 22.12241893, 38.94968492,
        3.32154645, 86.30631426, 93.11911478, 86.34103687, 85.30045256,
       77.02688233, 41.10441834, 80.86001257, 65.38514002, 81.73630268,
       14.48720941, 76.4740762 , 96.13132157,  1.92648736, 35.26543091,
       41.74848611, 87.11014711, 18.10028186,  3.20380073, 37.95866995,
       41.39788553, 87.73433244, 59.76605532, 24.8499454 , 73.51428294])

In [15]:
int_df_exams = np.random.uniform(1, 100, size= 1000)

In [18]:
df_exams['language_score'] = int_df_exams

In [19]:
df_exams

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,language score,language_score
0,female,group B,bachelor's degree,standard,none,72,72,74,25,42.368477
1,female,group C,some college,standard,completed,69,90,88,91,76.269655
2,female,group B,master's degree,standard,none,90,95,93,84,24.734618
3,male,group A,associate's degree,free/reduced,none,47,57,44,72,20.735646
4,male,group C,some college,standard,none,76,78,75,48,63.494580
...,...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95,51,71.144855
996,male,group C,high school,free/reduced,none,62,55,55,64,25.704405
997,female,group C,high school,free/reduced,completed,59,71,65,44,99.265096
998,female,group D,some college,standard,completed,68,78,77,53,5.642773
999,female,group D,some college,free/reduced,none,77,86,86,79,72.856626

In [25]:
round(df_exams,1)

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,language score,language_score
0,female,group B,bachelor's degree,standard,none,72,72,74,25,42.4
1,female,group C,some college,standard,completed,69,90,88,91,76.3
2,female,group B,master's degree,standard,none,90,95,93,84,24.7
3,male,group A,associate's degree,free/reduced,none,47,57,44,72,20.7
4,male,group C,some college,standard,none,76,78,75,48,63.5
...,...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95,51,71.1
996,male,group C,high school,free/reduced,none,62,55,55,64,25.7
997,female,group C,high school,free/reduced,completed,59,71,65,44,99.3
998,female,group D,some college,standard,completed,68,78,77,53,5.6
999,female,group D,some college,free/reduced,none,77,86,86,79,72.9